//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommunalServicesApp.ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reports
    {
        public int ReportId { get; set; }
        public int ServiceTypeId { get; set; }
        public string Title { get; set; }
        public string Note { get; set; }
        public int ClientId { get; set; }
        public System.DateTime Datetime { get; set; }
        public int StatusId { get; set; }
        public int WorkerId { get; set; }
        public int PriorityId { get; set; }
        public bool IsActual { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual Priorities Priorities { get; set; }
        public virtual ServiceTypes ServiceTypes { get; set; }
        public virtual Statuses Statuses { get; set; }
        public virtual Workers Workers { get; set; }
    }
}
