//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommunalServicesApp.ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reviews
    {
        public int ReviewId { get; set; }
        public int ClientId { get; set; }
        public int Rating { get; set; }
        public string Note { get; set; }
        public System.DateTime Datetime { get; set; }
    
        public virtual Clients Clients { get; set; }
    }
}
